version: '2'
services:
    bvrio-app:
        image: bvrio
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:postgresql://bvrio-postgresql:5432/bvrio
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    bvrio-postgresql:
        extends:
            file: postgresql.yml
            service: bvrio-postgresql
